### ISSUE TITLE
HVAC modes for maxcube

### ISSUE THREAD

**Issue by totti4ever** [fineemb/lovelace-thermostat-card#13]
Hey, I absolutely love your card! And I got it basically working.

The thing is, I cannot really use the hvac mode. When I click on the symbol, it fills out the whole card and when I click on it again it says _Failed to call service climate/set_hvac_mode._
```txt
2020-02-19 22:41:11 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139732047504912]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1226, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1251, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 198, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 356, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 384, in _handle_service_platform_call
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 422, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 418, in set_hvac_mode
    raise NotImplementedError()
NotImplementedError
```

I was hoping I could switch between the original modes of the thermostat, which are auto, boost, manual and vacation.

The sensor in HA looks like this in Auto mode:
```txt
hvac_modes: auto
min_temp: 4.5
max_temp: 30.5
preset_modes: boost,manual,vacation
current_temperature: 22.8
temperature: 21
preset_mode: null
friendly_name: Bad
supported_features: 17
```

and like this in manual mode:
```
hvac_modes: auto
min_temp: 4.5
max_temp: 30.5
preset_modes: boost,manual,vacation
current_temperature: 22.9
temperature: 16.5
preset_mode: manual
friendly_name: Bad
supported_features: 17
```

Any chance to reflect that?

**Comment by fineemb** [comment]
I am considering a solution that is compatible with all states
Later versions may be implemented one after another

**Comment by fineemb** [comment]
Hi
How is the status displayed on HASS?
And control what services the device uses?

**Comment by totti4ever** [comment]
The left one is not active (window opened, target temp 5°C), the right one is heating:
<img width="679" alt="ha" src="https://user-images.githubusercontent.com/49901208/75112562-53fc5780-5645-11ea-80c2-049531d29420.png">

**Comment by fineemb** [comment]
I need to see these two screenshots.
Usually control which service in the second picture is used

![01](https://user-images.githubusercontent.com/16739914/75112638-a73fcb80-5680-11ea-92c3-9d4c5976b621.jpg)
![02](https://user-images.githubusercontent.com/16739914/75112640-a9098f00-5680-11ea-9485-980b6c2b8181.jpg)

**Comment by totti4ever** [comment]
You can see the output in my earlier post. The services seem to be fully available in the drop-down, no matter what is supported as the service is chosen first and only then the entity
